### ISSUE TITLE
Использование в госорганах

### ISSUE THREAD

**Issue by theOneV** [AlexMAS/GostCryptography#1]
Александр, интересует вопрос относительно необходимости сертификации вашего ПО в госорганах.

Я правильно понимаю, что ваш .Net-провайдер использует исключительно интерфейс Microsoft CryptoAPI и через него обращается к крипто-провайдеру КриптоПро CSP или ViPNet CSP? Реализации самих алгоритмов шифрования в GostCryptography нет?

Таким образом, сертификация ФСТЭК не требуется? Или какие-то алгоритмы криптозащиты всё же есть в библиотеке?

**Comment by AlexMAS** [comment]
Здравствуйте. Да, все верно. Данная библиотека представляет собой .net-обертку над предустановленным криптопровайдером (КриптоПро CSP или ViPNet CSP), собственные алгоритмы она не реализует. Что касается сертификации ФСТЭК подсказать не могу, но, думаю, что она не требуется в этом случае. Тем не менее, лучше проконсультироваться у соответствующих специалистов, если это настолько важно для вас.

**Comment by theOneV** [comment]
Здравствуйте. Благодарю за ответ и за вашу замечательную библиотеку!

**Comment by AlexMAS** [comment]
Спасибо за отзыв. Примеры использования можете посмотреть по следующей ссылке, они выполнены в виде unit-тестов - https://github.com/AlexMAS/GostCryptography/tree/master/Source/GostCryptography.Tests
