### ISSUE TITLE
Ошибка установки пароля для контейнера

### ISSUE THREAD

**Issue by DPonomarchuk** [AlexMAS/GostCryptography#10]
Добрый день. При попытке задать пароль для контейнера закрытого ключа получаю исключение:

> Методу "GostCryptography.Gost_R3410.Gost_R3410_AsymmetricAlgorithm`2<TKeyParams,TKeyAlgorithm>.SetSignatureKeyPassword(GostCryptography.Native.SafeProvHandleImpl,
> 
>  System.Security.SecureString, Int32)", прозрачному для безопасности, не удалось получить доступ к критически важному типу безопасности "GostCryptography.Native.SafeProvHandleImpl".
> 
> Сборка "GostCryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" помечена атрибутом AllowPartiallyTrustedCallersAttribute и использует модель прозрачности безопасности уровня 2. Прозрачность уровня 2 делает все методы в сборках AllowPartiallyTrustedCallers прозрачными для безопасности по умолчанию, что может являться причиной этого исключения.

Пример кода:
```
var pars = x509Certificate.GetPrivateKeyInfo();
		    var gostR3410alg = new Gost_R3410_2001_AsymmetricAlgorithm(pars);
		    gostR3410alg.SetContainerPassword(s); // s - SecureString
			return gostR3410alg; // Ошибка
```
Может быть я делаю что-то не так и есть какой-то другой способ? В прошлой версии это работало.  Аналогичная ошибка и для Gost_R3410_2012_256_AsymmetricAlgorithm и Gost_R3410_2012_512_AsymmetricAlgorithm

**Comment by AlexMAS** [comment]
Спасибо за отзыв. Да, ошибка действительно была. Исправление доступно в [v2.0.1](https://www.nuget.org/packages/GostCryptography/2.0.1) (я только что его опубликовал, возможно, нужно некоторое время, чтобы вы могли его загрузить).

**Comment by AlexMAS** [comment]
Если ошибка больше не проявляется, предлагаю закрыть задачу. :)

**Comment by DPonomarchuk** [comment]
Да, всё работает корректно, спасибо
