### ISSUE TITLE
SignatureDescription could not be created for the signature algorithm supplied

### ISSUE THREAD

**Issue by FreeDarkKnight** [AlexMAS/GostCryptography#11]
Добрый день!

При подписании XML и указания 
`SignedXml.SignedInfo.SignatureMethod = "http://www.w3.org/2001/04/xmldsig-more#gostr34102001-gostr3411"`
возникает ошибка 

> System.Security.Cryptography.CryptographicException: SignatureDescription could not be created for the signature algorithm supplied

А при указании `SignedXml.SignedInfo.SignatureMethod = "urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102001-gostr3411"`

ругается проверка СМЭВ: 

> The requested algorithm urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102001-gostr3411 does not exist. Original Message was: null

Что я делаю не так?)

Ожидания СМЭВ:
```
	<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
			<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#gostr34102001-gostr3411" />
			<ds:Reference URI="#PERSONAL_SIGNATURE">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#gostr3411" />
				<ds:DigestValue/>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue/>
		<ds:KeyInfo>
			<ds:X509Data>
				<ds:X509Certificate/>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
```
Реальность, которая у меня получилась:
```
	<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
			<SignatureMethod Algorithm="urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102001-gostr3411" />
			<Reference URI="#PERSONAL_SIGNATURE">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
					<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#gostr3411" />
				<DigestValue/>
			</Reference>
		</SignedInfo>
		<SignatureValue/>
		<KeyInfo>
			<X509Data>
				<X509Certificate/>
			</X509Data>
		</KeyInfo>
	</Signature>
```

**Comment by AlexMAS** [comment]
Здравствуйте, спасибо за репорт.

Очевидно СМЭВ использует [устаревший идентификатор](https://tools.ietf.org/html/draft-chudov-cryptopro-cpxmldsig-08#section-6.5) для `SignatureMethod`. Для совместимости я зарегистрировал (указанный вами) дополнительный идентификатор для алгоритма подписи `2001` года:
```
http://www.w3.org/2001/04/xmldsig-more#gostr34102001-gostr3411
```
Исправление доступно в [v2.0.2](https://www.nuget.org/packages/GostCryptography/2.0.2). Если ошибка больше не проявляется, предлагаю закрыть задачу.

**Comment by FreeDarkKnight** [comment]
Добрый день!

Ошибки нет!

Огромное Вам спасибо за это проект и быстрый ответ!
