### ISSUE TITLE
win2008r2 + cryptopro5 + gost r2012-256

### ISSUE THREAD

**Issue by bor2001** [AlexMAS/GostCryptography#14]
возможно причина в платформе, но именно такая конфигурация довольно часто имеется у клиентов: winserver2008r2 + crypto-pro5.0.11319.
сертификат с гост2012-256.
при указании сертификата для подписания получаю ошибку:

Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GostCryptography.Gost_R3410.Gost_R3410_AsymmetricAlgorithm`2..ctor(CspParameters providerParameters, Int32 keySize)
   at System.Security.Cryptography.X509Certificates.X509CertificateHelper.GetPrivateKeyAlgorithm(X509Certificate2 certificate)
   at GostCryptography.Xml.GostSignedXml.SetSigningCertificate(X509Certificate2 certificate)

**Comment by bor2001** [comment]
csp был обновлён с 4.0.9929, где была та же ошибка

**Comment by AlexMAS** [comment]
@bor2001 Спасибо за отзыв. Есть возможность приложить полный стек исключений и указать версию .NET Framework? У пользователя, от имени которого выполняется приложение, есть доступ к контейнеру private-ключей?

**Comment by bor2001** [comment]
это полный стек, выше только моя функция - в основе код из примера дополненный общением с сервером данных mssql.
доступ у пользователя конечно есть к ключам.
ms .net framework 4 client profile
ms .net framework 4 extended

**Comment by bor2001** [comment]
доступ у пользователя конечно есть к ключам.

**Comment by AlexMAS** [comment]
А v1.0.1 там работает?

**Comment by bor2001** [comment]
там гост2012 теперь везде...

**Comment by bor2001** [comment]
извиняюсь за беспокойство - работает - ошибка была до перезагрузки после переустановки csp
