### ISSUE TITLE
А подписывать можно только HASH данных?

### ISSUE THREAD

**Issue by bitrix1** [AlexMAS/GostCryptography#20]
Здравствуйте.
Есть ли возможность подписывать сообщение, а не HASH, чтобы сделать один файл с прикрепленной подписью?
Например для просмотра через КриптоАрм.
http://cpdn.cryptopro.ru/content/cades/plugin-samples-sign-detached.html

Вот что я имею в виду:
JavaScript
```
var oSignedData = cadesplugin.CreateObject("CAdESCOM.CadesSignedData");
oSignedData.Content = dataToSign; // тут передаются данные.
var sSignedMessage = oSignedData.SignCades(oSigner, CADESCOM_CADES_BES, detached=false); //это сообщение с прикрепленной подписью.
```
P.S.
На всякий случай, для проверки попробовал подписать данные в GostCryptography, и получил ошибку **System.ArgumentOutOfRangeException: "Hash size must be 64 bytes.** 
Подумал а вдруг получится, но нет :)
```
private static byte[] CreateSignature1(GostAsymmetricAlgorithm privateKey, byte[] msgBytes)
{
  return privateKey.CreateSignature(msgBytes);
}
```
Спасибо!

**Comment by bitrix1** [comment]
Кажется понял, нашел API SignedXml.
https://docs.microsoft.com/ru-ru/dotnet/api/system.security.cryptography.xml.signedxml?view=netframework-4.5
Попытался подсунуть ему `GostAsymmetricAlgorithm` в поле `signedXml.SigningKey` и получил "Сбой при создании ключа подписи.".
Потом увидел `GostCryptography.Xml.GostSignedXmlImpl`, наследника того самого `SignedXml` и понял, что тут как раз решалась эта проблема.
Файл xml из примера на сайте Microsoft не годится, нужен именно файл этого проекта `GostCryptography.Tests/Data/SignedXmlExample.xml`

**Comment by AlexMAS** [comment]
Здравствуйте. Если нужно подписать бинарные данные, также можно воспользоваться [CMS/PKCS#7](https://github.com/AlexMAS/GostCryptography/blob/master/Source/GostCryptography.Tests/Pkcs/SignedCmsSignTest.cs).
