### ISSUE TITLE
Поддержка dotnetcore

### ISSUE THREAD

**Issue by iWeaverMan** [AlexMAS/GostCryptography#25]
System.Security.Cryptography.CryptographicException : '1.2.643.7.1.1.2.2' is not a known hash algorithm.

**Comment by AlexMAS** [comment]
Здравствуйте. Библиотека не поддерживает .NET Core, пока что это только в планах.

**Comment by iWeaverMan** [comment]
Добрый день!
С помощью https://github.com/dangbee/DotNetHook/blob/master/DotNetHook/Hooks/ManagedHook.cs удалось подменить GetDigestAlgorithm но не понятно что там возвращать и по коду похоже что там другие объекты используются для создания хеша и подписи, похоже надо где то еще встраиваться и подменять методы.
