### ISSUE TITLE
Не проверяется подпись от ПФР (но проверяется онлайн на КриптоПро DSS)

### ISSUE THREAD

**Issue by Uriel6575** [AlexMAS/GostCryptography#30]
Времени суток!

Столкнулся со странной бедой: приходят подписанные файлы, которые не хотят проверяться. При том, что с виду там проблем никаких быть не должно.
И всё бы ничего, но их отлично проверяет сервис от КриптоПро! Вот этот: https://www.justsign.me/verifycpca/Verify/
Подпись, сделанную GostCryptography, он, напротив, проверять не хочет.

Я в мат. части тут не очень силён, поэтому могу упускать что-то очень очевидное. Для проверки брал метод VerifyXmlDocumentSignature из тестов.
Заранее благодарен за помощь!

**Comment by AlexMAS** [comment]
Здравствуйте. Обычно у каждой организации есть свои требования/спецификации по интергации, поэтому трудно сказать о причинах проблемы. Например, была достаточно долгая дискуссия про [интеграцию с ФСС](https://github.com/AlexMAS/GostCryptography/issues/26). Возможно, это обсуждение поможет найти причину ошибки. Может быть нужно подписать не весь документ, а только какую-то его часть. Также проверьте, что идентификаторы алгоритмов именно те, которые ожидает ПФР (практика подсказывает, что иногда принимающая сторона ожидает что-то другое, отличное от ГОСТ, тогда при создании подписи нужно явно указать идентификатор того алгоритма, который они ожидают). К сожалению, у меня нет опыта интеграции с ПФР, поэтому я не могу помочь вам предметно. Если что-то получится, можете поделиться результатами. ;)

**Comment by Uriel6575** [comment]
Благодарю за ответ. На самом деле 4 часа экспериментов привели к тому, что надо просто правильно "играться" опциями PreserveWhitespace и Indent в reader'ах и writer'ах, чтобы его удовлетворить. Может быть кому-нибудь и пригодится эта информация. Портал КриптоПро мою подпись уже проверяет корректно. У меня получилось проверить их подпись, но пока затык с тем, что хэш не соответствует содержимому. Но это уже мелочи и наверное тоже решится.
