### ISSUE TITLE
СМЭВ 3.0

### ISSUE THREAD

**Issue by odmion** [AlexMAS/GostCryptography#4]
В связи с выходом новой версии СМЭВ было бы неплохо обновить SmevExample.xml SignedXmlSmevTest.cs в GostCryptography.Tests

**Comment by odmion** [comment]
Мне практически удалось создать xml для СМЭВ 3.0.
Не могу добавить второй алгоритм нормализации как указано в примерах.
Ссылка на примеры: https://smev3.gosuslugi.ru/portal/api/files/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B.zip

**Comment by AlexMAS** [comment]
Спасибо за отзыв. Я уже не совсем в контексте этого вопроса, но буду рад увидеть новый XML и ваше решение. По поводу примеров, я постараюсь их посмотреть.

**Comment by AlexMAS** [comment]
Можно ли считать данный вопрос решенным?
