### ISSUE TITLE
Принудительное шифрование XML по ГОСТ 2001

### ISSUE THREAD

**Issue by das511** [AlexMAS/GostCryptography#44]
Приветствую, есть задача принудительно шифровать XML по ГОСТ 2001 года, подскажите, как это можно сделать и можно ли вообще...

**Comment by AlexMAS** [comment]
Здравствуйте. Шифровать или всё-таки подписывать? И что значит "принудительно"?

**Comment by das511** [comment]
Если использовать сертификат который поддерживает шифрование по ГОСТ 2012 то по умолчанию при использовании метода GostEncryptedXml.Encrypt() шифрование будет по ГОСТ 2012, а мне необходимо принудительно шифровать по ГОСТ 2001

**Comment by AlexMAS** [comment]
С трудом представляю, зачем такое нужно... Можно посмотреть, как реализован [`GostEncryptedXmlImpl.Encrypt()`](https://github.com/AlexMAS/GostCryptography/blob/master/Source/GostCryptography/Xml/GostEncryptedXmlImpl.cs#L62) и сделать что-то свое. Например, захардкодить установку `EncryptionMethod`. Но вообще говоря, с новым сертификатом 2012 шифрование общего секретного ключа все равно будет идти по алгоритмам 2012 года. Либо придется лезть еще глубже.
