### ISSUE TITLE
Поддержка ГОСТ 34.12-2018

### ISSUE THREAD

**Issue by CrazyB0y** [AlexMAS/GostCryptography#52]
Доброго дня

А планируется ли поддержка ГОСТ 34.12-2018 (Магма и Кузнечик, бывшие ГОСТ Р 34.12-2015)

P.S. Спасибо за либу

**Comment by AlexMAS** [comment]
Здравствуйте!

Постараюсь добавить в ближайшее время. Пока не вижу сложности в этом.

**Comment by AlexMAS** [comment]
Опишите, пожалуйста, пользовательский сценарий, что именно хотите сделать с использованием этих алгоритмов. Чтобы я смог написать какие-то тесты на нужную функциональность.

**Comment by CrazyB0y** [comment]
Например, выполнить шифрование XML сессионным ключом

Но вместо `Gost_28147_89_SymmetricAlgorithm` использовать условный `Gost_34_12_2018_SymmetricAlgorithm`

```csharp
    var publicKeyAlgorithm = (GostAsymmetricAlgorithm)certificate.GetPublicKeyAlgorithm();
    var sessionKey = new Gost_28147_89_SymmetricAlgorithm(publicKeyAlgorithm.ProviderType);
    
    elementEncryptedData.EncryptionMethod = new EncryptionMethod(sessionKey.AlgorithmName);
    
    var encryptedXml = new GostEncryptedXml();
    var xmlBytes = Encoding.UTF8.GetBytes(inputXmlDoc.OuterXml);
    var encryptedData = encryptedXml.EncryptData(xmlBytes, sessionKey);
    
    elementEncryptedData.CipherData.CipherValue = encryptedData;
    
    var encryptMethod = new EncryptionMethod(publicKeyAlgorithm.KeyExchangeAlgorithm);
    var encryptedSessionKeyData = GostEncryptedXml.EncryptKey(sessionKey, publicKeyAlgorithm);
    var encryptedSessionKey = new EncryptedKey
    {
        CipherData = new CipherData(encryptedSessionKeyData),
        EncryptionMethod = encryptMethod,
    };
    
    encryptedSessionKey.KeyInfo.AddClause(new KeyInfoX509Data(certificate));
    elementEncryptedData.KeyInfo.AddClause(new KeyInfoEncryptedKey(encryptedSessionKey));
```

Проверить бы ещё работу Pkcs и реализовать необходимые механизмы, если конечно оно не работает сейчас с указанием нужных Oid для шифрования

**Comment by AlexMAS** [comment]
@CrazyB0y Здравствуйте! Если у вас есть возможность, можете посмотреть функциональность в ветке `magma-and-kuznyechik`. Примеры тестов с шифрованием XML можно найти тут:

* [`MagmaEncryptedXmlCertificateTest.cs`](https://github.com/AlexMAS/GostCryptography/blob/magma-and-kuznyechik/Source/GostCryptography.Tests/Xml/Encrypt/MagmaEncryptedXmlCertificateTest.cs)
* [`KuznyechikEncryptedXmlCertificateTest.cs`](https://github.com/AlexMAS/GostCryptography/blob/magma-and-kuznyechik/Source/GostCryptography.Tests/Xml/Encrypt/KuznyechikEncryptedXmlCertificateTest.cs)

Если всё ОК, опубликую новую версию пакета.

**Comment by CrazyB0y** [comment]
Доброго вечера

Вернусь с обратной связью через 3-4 дня
Благодарю за быструю реакцию

**Comment by CrazyB0y** [comment]
Да, всё отлично, для моего использования всё работает корректно!

Спасибо за помощь

**Comment by AlexMAS** [comment]
Спасибо за обратную связь! :)

Я опубликовал новую версию на NuGet (см. [2.0.11](https://www.nuget.org/packages/GostCryptography/2.0.11)).
