### ISSUE TITLE
Поддержка криптопровайдеров с ГОСТ-2012

### ISSUE THREAD

**Issue by DmitriyBorodulin** [AlexMAS/GostCryptography#8]
Добрый день!

Планируется ли такая возможность?

**Comment by AlexMAS** [comment]
Здравствуйте. Хотелось бы найти время на реализацию этой функциональности. Пока по срокам сказать ничего не могу, к сожалению. Возможно, в начале июля начну смотреть, что можно сделать.

**Comment by DPonomarchuk** [comment]
Добрый день, есть ли какие-то продвижения в этом направлении и планируются ли?

**Comment by IronRate** [comment]
> Добрый день, есть ли какие-то продвижения в этом направлении и планируются ли?

Если Вам достаточно будет подписи, то можете воспользоватся данным [форком,](https://github.com/IronRate/GostCryptography) но есть некоторые различия от оригинала.

**Comment by AlexMAS** [comment]
Выпустил [v2.0.0](https://www.nuget.org/packages/GostCryptography/2.0.0), которая включает поддержку алгоритмов `2012` года, а также исправление известных ошибок совместимости с `ViPNet CSP 4.2`. Версия была протестирована на конфигурациях:

* Windows 10 x64, CryptoPro CSP 4.0.9963
* Windows 10 x64, ViPNet CSP 4.2.8.51670

В случае с `CryptoPro CSP` важно установить версию не ниже `4.0.9963` (на момент тестирования последний private-релиз), поскольку она содержит исправление [критической ошибки](https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=14515&p=2) при работе с сертификатами `ГОСТ Р 34.10-2012/1024`.

Также нужно отметить, что `ViPNet CSP` до последней на данный момент версии `4.2.8.51670` (включительно) [не поддерживает создание производных симметричных ключей](https://infotecs.ru/forum/topic/10142-oshibka-pri-sozdanii-klyucha-shifrovaniya-na-osnove-dannyih-polzovatelya-cryptderivekey/) на основе хэш-функций `ГОСТ﻿ Р 34.11-20﻿12﻿﻿`. Ничего критичного в этом нет, это оказывает влияние только на возможность генереции случайных симметричных ключей с использованием методов `Gost_R3411_2012_256_PRF.DeriveKey()` и `Gost_R3411_2012_512_PRF.DeriveKey()`.

Наконец, в ходе добавления поддержки алгоритмов `2012` года были произведены крупные изменения, включающие перенос/переименование существующих классов. Для перехода с `v1.0` на `v2.0` нужно воспользоваться [следующей иструкцией](https://github.com/AlexMAS/GostCryptography/wiki/Migration-Guide).
